# DATAFRAME

CREATING A DATAFRAME

-> creating a new column

-> removing columns

-> selecting rows

-> selecting subsets fo rows and columns

-> conditional selection

In [66]:
import numpy as np
import pandas as pd

In [67]:
data = {
    'Name' :['john' , 'adi' , 'noni'],
    'Age' : [20 , 21 , 22],
    'City' : ['New york' , 'Paris' , 'France'],
    'Salary' : [65000 , 78000 , 70000]

}
pd.DataFrame(data)

   Name  Age      City  Salary
0  john   20  New york   65000
1   adi   21     Paris   78000
2  noni   22    France   70000

In [86]:
data_list = [
    ['john' , 'adi' , 'noni'],
    [20 , 21 , 22],
    ['New york' , 'Paris' , 'France'],
    [65000 , 78000 , 70000]

]
df2 = pd.DataFrame(data_list)
columns = ["Name", "Age", "City", "Salary"]
df2 = pd.DataFrame(data_list).T
df2.columns = columns
df2

   Name Age      City Salary
0  john  20  New york  65000
1   adi  21     Paris  78000
2  noni  22    France  70000

SELECTION AND INDEXING OF COLUMNS

In [87]:
df2

   Name Age      City Salary
0  john  20  New york  65000
1   adi  21     Paris  78000
2  noni  22    France  70000

In [90]:
df2['Name']

0    john
1     adi
2    noni
Name: Name, dtype: object

In [91]:
df2[['Name','Age']]

   Name Age
0  john  20
1   adi  21
2  noni  22

CREATING A NEW COLUMN

In [93]:
df2["Desigination"] = ["Doctor" , "businessman" , "engineer"]

REMOVING COLUMNS

SELECTING ROWS

In [94]:
df2

   Name Age      City Salary Desigination
0  john  20  New york  65000       Doctor
1   adi  21     Paris  78000  businessman
2  noni  22    France  70000     engineer

In [95]:
df2['City']

0    New york
1       Paris
2      France
Name: City, dtype: object

In [96]:
print(df2.columns)

Index(['Name', 'Age', 'City', 'Salary', 'Desigination'], dtype='str')

In [97]:
print(df2)
print(df2.columns.tolist())

   Name Age      City Salary Desigination
0  john  20  New york  65000       Doctor
1   adi  21     Paris  78000  businessman
2  noni  22    France  70000     engineer
['Name', 'Age', 'City', 'Salary', 'Desigination']

CONDITIONAL STATEMENTS

In [98]:
df2[df2['Age'] > 20]

   Name Age    City Salary Desigination
1   adi  21   Paris  78000  businessman
2  noni  22  France  70000     engineer

In [104]:
df2[(df2['Age'] == 21) & (df2['City'] == "Paris")]

  Name Age   City Salary Desigination
1  adi  21  Paris  78000  businessman