In [2]:
import numpy as np
import pandas as pd

Merging Two Dataframes

In [3]:
employees = pd.DataFrame({
    "employee_id" : [1 , 2 , 3 ],
    "name" : ["Deepti" , "Aditya" , "Ishita"],
    "department" : ["CSE" , "BCA" , "HR" ]
})
salaries = pd.DataFrame({
    "employee_id" : [1 , 2 , 3 ],
    "salary" : [20000 , 30000 , 40000],
    "bonus" : [5000 , 10000 , 40000]
})

In [4]:
employees

   employee_id    name department
0            1  Deepti        CSE
1            2  Aditya        BCA
2            3  Ishita         HR

In [5]:
salaries

   employee_id  salary  bonus
0            1   20000   5000
1            2   30000  10000
2            3   40000  40000

In [6]:
pd.merge(employees , salaries, on="employee_id", how = "inner")

   employee_id    name department  salary  bonus
0            1  Deepti        CSE   20000   5000
1            2  Aditya        BCA   30000  10000
2            3  Ishita         HR   40000  40000

In [7]:
pd.merge(employees , salaries, on="employee_id", how = "outer")

   employee_id    name department  salary  bonus
0            1  Deepti        CSE   20000   5000
1            2  Aditya        BCA   30000  10000
2            3  Ishita         HR   40000  40000

In [8]:
pd.merge(employees , salaries, on="employee_id", how = "left")

   employee_id    name department  salary  bonus
0            1  Deepti        CSE   20000   5000
1            2  Aditya        BCA   30000  10000
2            3  Ishita         HR   40000  40000

CONCATENATION

In [9]:
df1 = pd.DataFrame({
    "A" : ["A0" , "A1" , "A2" ],
    "B" : ["B0" , "B1" , "B2" ],
    "C" : ["C0" , "C1" , "C2" ]
})
df2 = pd.DataFrame({
    "A" : ["A3" , "A4" , "A5" ],
    "B" : ["B3" , "B4" , "B5" ],
    "C" : ["C3" , "C4" , "C5" ]
})

In [10]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [11]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [12]:
pd.concat([df1 , df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [13]:
pd.concat([df1 , df2] , axis = 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

JOINING DATAFRAMES

In [14]:
df1 = pd.DataFrame({
    "name" : ["Deepti" , "Aditya" , "Ishita"]
} , index = [1 , 2 , 3])

df2 = pd.DataFrame({
    "score" : [67 , 80 , 75]
} , index = [2 , 3 , 4])

In [15]:
df1

     name
1  Deepti
2  Aditya
3  Ishita

In [16]:
df2

   score
2     67
3     80
4     75

In [18]:
df1.join(df2 , how = "outer")

     name  score
1  Deepti    NaN
2  Aditya   67.0
3  Ishita   80.0
4     NaN   75.0